# Example: CI Workflow with Gemini AI Integration
# This template shows how to integrate Gemini AI analysis with the CI Framework

name: CI with Gemini AI Analysis

on:
  push:
    branches: [main, master, development]
  pull_request:
    branches: [main, master, development]
  workflow_dispatch:
    inputs:
      force_full_ci:
        description: 'Force full CI (skip optimizations)'
        required: false
        default: 'false'
        type: boolean
      ai_analysis_type:
        description: 'AI analysis type'
        required: false
        default: 'pr-review'
        type: choice
        options:
          - 'pr-review'
          - 'comprehensive'
          - 'security-analysis'
          - 'performance-analysis'

# Required permissions for Gemini AI integration
permissions:
  contents: read
  pull-requests: write
  issues: write
  actions: read
  security-events: write

env:
  # Enable AI analysis - controlled by repository variable
  ENABLE_AI_ANALYSIS: ${{ vars.ENABLE_AI_ANALYSIS == 'true' }}

jobs:
  # Main CI workflow with AI integration
  ci:
    name: CI Framework with AI
    uses: Claire-s-Monster/ci-framework/.github/workflows/reusable-ci.yml@v1.1.0
    with:
      # CI Configuration
      tier: 'comprehensive'  # essential|comprehensive|extended
      enable-ai-analysis: ${{ vars.ENABLE_AI_ANALYSIS == 'true' }}
      force-full-ci: ${{ github.event.inputs.force_full_ci == 'true' }}
      
      # Quality Configuration
      fail-fast: true
      parallel: true
      
      # Performance Configuration  
      performance-threshold: '15.0'  # 15% regression threshold
      enable-benchmarks: true
      
      # Security Configuration
      security-level: 'high'  # low|medium|high|critical
      enable-sarif: true
      enable-sbom: true
      
      # Platform Configuration
      platforms: '["ubuntu-latest", "windows-latest", "macos-latest"]'
      
    secrets:
      # Required for AI analysis
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      # Pass through other secrets as needed
      inherit

  # Additional AI Analysis (Optional - for detailed analysis)
  detailed-ai-analysis:
    name: Detailed AI Analysis
    needs: ci
    if: |
      always() && 
      github.event_name == 'pull_request' && 
      vars.ENABLE_AI_ANALYSIS == 'true' &&
      (
        contains(github.event.pull_request.labels.*.name, 'ai-review') ||
        github.event.pull_request.changed_files > 10 ||
        contains(github.event.pull_request.title, '[major]')
      )
    
    uses: Claire-s-Monster/ci-framework/.github/workflows/gemini-ai-analysis.yml@v1.1.0
    with:
      analysis_type: ${{ github.event.inputs.ai_analysis_type || 'comprehensive' }}
      focus_area: 'src/'  # Focus on source code changes
      prompt: |
        Perform detailed analysis considering the CI results:
        - Quality Gates: ${{ needs.ci.outputs.quality-status }}
        - Security Scan: ${{ needs.ci.outputs.security-status }}
        - Performance: ${{ needs.ci.outputs.performance-status }}
        
        Focus on:
        1. Impact of changes on system architecture
        2. Potential performance implications  
        3. Security considerations
        4. Code maintainability and technical debt
        5. Test coverage and quality
    
    secrets:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

  # Weekly Comprehensive Analysis (Optional)
  weekly-analysis:
    name: Weekly AI Health Check
    if: github.event_name == 'schedule' && vars.ENABLE_AI_ANALYSIS == 'true'
    
    uses: Claire-s-Monster/ci-framework/.github/workflows/gemini-ai-analysis.yml@v1.1.0
    with:
      analysis_type: 'comprehensive'
      prompt: |
        Perform weekly project health analysis:
        
        1. **Code Quality Trends**: Analyze changes over the past week
        2. **Technical Debt**: Identify accumulating technical debt
        3. **Security Posture**: Review security improvements/regressions  
        4. **Performance Trends**: Analyze performance impact of recent changes
        5. **Test Quality**: Evaluate test suite effectiveness
        6. **Documentation**: Check documentation completeness
        
        Provide strategic recommendations for improving project health.
    
    secrets:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

# Example schedule for weekly analysis (uncomment to enable)
# on:
#   schedule:
#     - cron: '0 9 * * MON'  # Every Monday at 9 AM UTC

---
# SETUP INSTRUCTIONS:
#
# 1. Repository Secrets (required):
#    - GEMINI_API_KEY: Your Google AI Studio API key
#
# 2. Repository Variables (required):
#    - ENABLE_AI_ANALYSIS: 'true' (to enable AI features)
#
# 3. Repository Variables (optional):
#    - AI_ANALYSIS_LEVEL: 'standard' (basic|standard|comprehensive)
#    - GEMINI_MODEL: 'gemini-2.0-flash-exp' (AI model to use)
#
# 4. Labels (optional, for enhanced workflows):
#    Create these labels in your repository:
#    - 'ai-review': Triggers detailed AI analysis
#    - 'security-review': Focuses AI on security aspects
#    - 'performance-review': Focuses AI on performance aspects
#
# 5. Team Configuration (optional):
#    Create .github/CODEOWNERS for AI to understand team structure
#
# 6. Custom Prompts (optional):
#    Create .github/gemini-prompts.yml for custom analysis prompts

# COST CONSIDERATIONS:
# 
# Gemini API usage is billed per token. Typical usage:
# - Basic PR review: ~1,000-3,000 tokens
# - Comprehensive analysis: ~5,000-10,000 tokens  
# - Weekly analysis: ~10,000-20,000 tokens
#
# Monitor usage in Google AI Studio console and adjust analysis
# frequency/scope based on your budget and needs.

# TEAM WORKFLOW INTEGRATION:
#
# 1. Use AI analysis to supplement (not replace) human code review
# 2. Train team to interpret and act on AI recommendations
# 3. Use labels to trigger deeper analysis for complex changes
# 4. Create feedback loops to improve AI prompt quality
# 5. Monitor AI analysis quality and adjust configuration