name: "🔧 Self-Healing CI"

on:
  workflow_call:
    inputs:
      healing-level:
        description: "Healing intensity: quick, standard, comprehensive"
        required: false
        default: 'standard'
        type: string
      auto-fix:
        description: "Enable automatic fixes for detected issues"
        required: false
        default: true
        type: boolean
      rollback-on-failure:
        description: "Rollback changes if healing fails"
        required: false
        default: true
        type: boolean
      timeout-minutes:
        description: "Timeout for healing process"
        required: false
        default: 10
        type: number
      pixi-environment:
        description: "PIXI environment to use for healing"
        required: false
        default: 'dev'
        type: string
    outputs:
      healed:
        description: "Whether healing was successfully applied"
        value: ${{ jobs.self-healing.outputs.healed }}
      rollback-triggered:
        description: "Whether rollback was triggered"
        value: ${{ jobs.self-healing.outputs.rollback }}
      fixes-applied:
        description: "Number of fixes applied during healing"
        value: ${{ jobs.self-healing.outputs.fixes-applied }}

jobs:
  self-healing:
    name: "🔧 Self-Healing CI"
    runs-on: ubuntu-latest
    timeout-minutes: ${{ fromJSON(inputs.timeout-minutes) }}
    
    outputs:
      healed: ${{ steps.healing.outputs.healed }}
      rollback: ${{ steps.healing.outputs.rollback }}
      fixes-applied: ${{ steps.healing.outputs.fixes-applied }}
    
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.CI_BOT_TOKEN || github.token }}
      
      - name: "Run Self-Healing Engine"
        id: healing
        uses: ./actions/self-healing
        with:
          healing-level: ${{ inputs.healing-level }}
          auto-fix: ${{ inputs.auto-fix }}
          rollback-on-failure: ${{ inputs.rollback-on-failure }}
          timeout-minutes: ${{ inputs.timeout-minutes }}
          pixi-environment: ${{ inputs.pixi-environment }}
      
      - name: "Commit Healing Changes"
        if: steps.healing.outputs.healed == 'true'
        run: |
          git config --global user.name "ci-framework-bot"
          git config --global user.email "ci-framework-bot@noreply.github.com"
          
          # Import GPG key for signing
          if [ -n "${{ secrets.CI_BOT_GPG_KEY }}" ]; then
            echo "${{ secrets.CI_BOT_GPG_KEY }}" | gpg --import --batch
            git config --global user.signingkey ${{ secrets.CI_BOT_GPG_KEY_ID }}
            git config --global commit.gpgSign true
          fi
          
          # Commit healing changes
          git add .
          git commit -m "fix: apply self-healing fixes - ${{ steps.healing.outputs.fixes-applied }} fixes applied

          Automated fixes applied by self-healing engine:
          - Healing level: ${{ inputs.healing-level }}
          - Fixes applied: ${{ steps.healing.outputs.fixes-applied }}
          - Auto-rollback: ${{ inputs.rollback-on-failure }}
          
          🤖 Generated by Self-Healing CI Framework
          Co-Authored-By: ci-framework-bot <ci-framework-bot@noreply.github.com>"
          
          # Push changes
          git push origin ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.CI_BOT_TOKEN || github.token }}
      
      - name: "Healing Summary"
        if: always()
        run: |
          echo "## 🔧 Self-Healing Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **Healing Level**: ${{ inputs.healing-level }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Auto-Fix Enabled**: ${{ inputs.auto-fix }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Rollback Enabled**: ${{ inputs.rollback-on-failure }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Healing Applied**: ${{ steps.healing.outputs.healed }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Fixes Applied**: ${{ steps.healing.outputs.fixes-applied }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Rollback Triggered**: ${{ steps.healing.outputs.rollback }}" >> $GITHUB_STEP_SUMMARY